"""Initial migration.

Revision ID: 2579065e80e6
Revises: 
Create Date: 2025-09-23 13:23:36.296587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2579065e80e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.alter_column('bank_account_number',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('bank_postal_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.alter_column('bank_postal_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('bank_account_number',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###
